### ISSUE TITLE
why hyphen is present in some tokens?

### ISSUE THREAD

**Issue by sm354** [juntaoy/aracoref#8]
Inside `preprocess_arabic.py` [this](https://github.com/juntaoy/aracoref/blob/main/preprocess_arabic.py#L13) line is commented which is meant to remove hyphens present in the data. If I uncomment this then I am able to get significantly higher scores (using other coref model, [icoref](https://github.com/pitrack/incremental-coref) on ontonotes-ar). Could you please tell why hyphens are kept in the data?

**Comment by juntaoy** [comment]
I used the converting script from Kenton Lee's original e2e-coref paper, so they didn't do anything with the hyphens. I thought this would be unfair if we remove them from the datasets.
